server:
  port: 8081

spring:
  cloud:
    openfeign:
      circuitbreaker:
          enabled: true
  application:
    name: client-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0